apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql  # Matches pods with the label 'app: mysql'
  ports:
    - protocol: TCP
      port: 3306  # MySQL port
      targetPort: 3306
