apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 512Mi  # Desired storage capacity
  accessModes:
    - ReadWriteOnce  # Access mode: ReadWriteOnce (single-node read/write)
  persistentVolumeReclaimPolicy: Retain  # Persistent volume reclaim policy
  storageClassName: mariadb-storage  # Storage class name
  hostPath:
    path: /data/mysql  # Host path where MySQL data will be stored
