apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1  # The desired number of MySQL replicas
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:dev # The MySQL image you wish to use
        ports:
        - containerPort: 3306  # MySQL port
        resources:
          limits:
            memory: "512Mi"   # Maximum memory limit
            cpu: "1"          # Maximum CPU usage limit
          requests:
            memory: "256Mi"   # Minimum memory request
            cpu: "0.5"         # Minimum CPU usage request
       # env:
        #  - name: MYSQL_ROOT_PASSWORD
        #    value: your-root-password  # Change this to your root password
        #  - name: MYSQL_DATABASE
        #    value: your-database-name  # Change this to your database name
        #readinessProbe:
        #  exec:
        #    command:
        #    - "sh"
        #    - "-c"
        #    - "mysqladmin ping -h 127.0.0.1 -u MYSQL_USER -p MYSQL_ROOT_PASSWORD"
        #  initialDelaySeconds: 5  # Initial delay before starting readiness probes
        #  periodSeconds: 10  # Frequency of readiness probes
        #livenessProbe:
        #  exec:
        #    command:
        #    - "sh"
        #    - "-c"
        #    - "mysqladmin ping -h 127.0.0.1 -u MYSQL_USER -p MYSQL_ROOT_PASSWORD"
        #  initialDelaySeconds: 15  # Initial delay before starting liveness probes
        #  periodSeconds: 10  # Frequency of liveness probes
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql  # Directory where persistent storage will be mounted
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc  # Name of the PVC you want to mount

