apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  volumeName: mariadb-pv
  accessModes:
    - ReadWriteOnce  # Access mode: ReadWriteOnce (matches PV)
  resources:
    requests:
      storage: 512Mi  # Requested storage amount
  storageClassName: mariadb-storage  # Storage class name (matches PV)
