apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  selector:
    app: mariadb  # Matches pods with the label 'app: mariadb'
  ports:
    - protocol: TCP
      port: 3306  # MySQL port
      targetPort: 3306
